<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>efa977d6-80da-4622-bd47-c0a30173f02e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.12.0" />
    <PackageReference Include="Ferremundo.Security.Authentication" Version="1.0.0-alpha.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.8.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ferremundo.Erp.Skus.Application\Ferremundo.Erp.Skus.Application.csproj" />
    <ProjectReference Include="..\Ferremundo.Erp.Skus.Infrastructure\Ferremundo.Erp.Skus.Infrastructure.csproj" />
    <ProjectReference Include="..\..\subModules\Internal\Ferremundo.Erp.Skus.Sdk\src\Ferremundo.Erp.Skus.Contracts\Ferremundo.Erp.Skus.Contracts.csproj" />
  </ItemGroup>
</Project>
